Updating the regex package version for compatibility with aho-corasick
This change aims to resolve the following error when generating the package for other versions of Ubuntu:

error: failed to select a version for the requirement aho-corasick = "^1.0.0"
candidate versions found which didn't match: 0.7.20, 0.7.19, 0.7.18, ...
location searched: crates.io index
required by package regex v1.8.1
... which satisfies dependency regex = "^1" (locked to 1.8.1) of package drib v1.0.0 (/builds/dml/debian/drib/drib)